version: '3.8'

services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
